Repository pubky/franky, pull requests merged in 2025-10, with the labels that each got.

#58 feat: hot tags
  src/components/atoms/Tag/Tag.test.tsx
  src/components/atoms/Tag/Tag.tsx
  src/components/atoms/Tag/index.ts
  src/components/atoms/index.ts
  src/components/molecules/HotTags/HotTags.test.tsx
  src/components/molecules/HotTags/HotTags.tsx
  src/components/molecules/HotTags/index.tsx
  src/components/molecules/index.ts
  src/libs/utils/utils.test.ts
  src/libs/utils/utils.ts
Labels: 📈 enhancement, 🎨 ui

#203 feat: add stream related nexus endpoints
  eslint.config.mjs
  src/components/atoms/Link/Link.test.tsx
  src/components/molecules/Content/Content.test.tsx
  src/components/molecules/DialogDownloadPubkyRing/DialogDownloadPubkyRing.test.tsx
  src/components/molecules/DialogExport/DialogExport.test.tsx
  src/components/molecules/DialogWelcome/DialogWelcome.test.tsx
  src/components/molecules/Header/Header.test.tsx
  src/components/molecules/Install/Install.test.tsx
  src/components/molecules/Logo/Logo.test.tsx
  src/components/molecules/Logout/Logout.test.tsx
  src/components/molecules/Scan/Scan.test.tsx
  src/components/molecules/SignIn/SignIn.test.tsx
  src/components/organisms/CreateProfileForm/CreateProfileForm.test.tsx
  src/components/organisms/PublicKeyCard/PublicKeyCard.test.tsx
  src/core/controllers/index.ts
  src/core/controllers/stream/index.ts
  src/core/controllers/stream/stream.ts
  src/core/controllers/stream/stream.types.ts
  src/core/services/nexus/index.ts
  src/core/services/nexus/stream/index.ts
  src/core/services/nexus/stream/posts/index.ts
  src/core/services/nexus/stream/posts/postStream.api.ts
  src/core/services/nexus/stream/posts/postStream.test.ts
  src/core/services/nexus/stream/posts/postStream.types.ts
  src/core/services/nexus/stream/users/index.ts
  src/core/services/nexus/stream/users/userStream.api.ts
  src/core/services/nexus/stream/users/userStream.ts
  src/core/services/nexus/stream/users/userStream.types.ts
Labels: 🔮 nexus

#209 tests: more snapshot tests
  src/components/atoms/Tag/Tag.test.tsx
  src/components/atoms/Tag/Tag.test.tsx.snap
  src/components/atoms/Toggle/Toggle.test.tsx
  src/components/atoms/Toggle/Toggle.test.tsx.snap
  src/components/molecules/Breadcrumb/Breadcrumb.test.tsx
  src/components/molecules/Breadcrumb/Breadcrumb.test.tsx.snap
Labels: 🧪 tests

#211 feat: implement backup flow with welcome dialog and alert
  src/components/molecules/AlertBackup/AlertBackup.test.tsx
  src/components/molecules/AlertBackup/AlertBackup.tsx
  src/components/molecules/DialogBackup/DialogBackup.tsx
  src/components/molecules/DialogBackupPhrase/DialogBackupPhrase.test.tsx.snap
  src/components/molecules/DialogBackupPhrase/DialogBackupPhrase.tsx
  src/components/molecules/DialogConfirmBackup/DialogConfirmBackup.tsx
  src/components/molecules/DialogExport/DialogExport.test.tsx
  src/components/molecules/DialogExport/DialogExport.test.tsx.snap
  src/components/molecules/DialogExport/DialogExport.tsx
  src/components/molecules/index.ts
  src/components/organisms/AlertBackup/AlertBackup.stories.tsx
  src/components/organisms/AlertBackup/AlertBackup.test.tsx
  src/components/organisms/AlertBackup/AlertBackup.test.tsx.snap
  src/components/organisms/AlertBackup/AlertBackup.tsx
  src/components/organisms/AlertBackup/index.tsx
  src/components/organisms/BackupMethodCard/BackupMethodCard.test.tsx
  src/components/organisms/BackupMethodCard/BackupMethodCard.tsx
  src/components/organisms/CreateProfileForm/CreateProfileForm.test.tsx
  src/components/organisms/CreateProfileForm/CreateProfileForm.tsx
  src/components/organisms/DialogBackup/DialogBackup.stories.tsx
  src/components/organisms/DialogBackup/DialogBackup.test.tsx
  src/components/organisms/DialogBackup/DialogBackup.test.tsx.snap
  src/components/organisms/DialogBackup/DialogBackup.tsx
  src/components/organisms/DialogBackup/index.tsx
  src/components/organisms/DialogBackupEncrypted/DialogBackupEncrypted.test.tsx
  src/components/organisms/DialogBackupEncrypted/DialogBackupEncrypted.test.tsx.snap
  src/components/organisms/DialogBackupEncrypted/DialogBackupEncrypted.tsx
  src/components/organisms/DialogBackupEncrypted/index.ts
  src/components/organisms/DialogConfirmBackup/DialogConfirmBackup.stories.tsx
  src/components/organisms/DialogConfirmBackup/DialogConfirmBackup.test.tsx
  src/components/organisms/DialogConfirmBackup/DialogConfirmBackup.tsx
  src/components/organisms/DialogConfirmBackup/index.ts
  src/components/organisms/index.ts
  src/components/templates/Feed/Feed.test.tsx
  src/components/templates/Feed/Feed.test.tsx.snap
  src/components/templates/Feed/Feed.tsx
  src/core/stores/onboarding/onboarding.actions.ts
  src/core/stores/onboarding/onboarding.store.test.ts
  src/core/stores/onboarding/onboarding.store.ts
  src/core/stores/onboarding/onboarding.types.ts
  src/hooks/useAuthActions/useAuthActions.tsx
Labels: 🎨 ui

#228 Fix failing onboarding E2E test
  cypress/e2e/onboarding.cy.ts
  cypress/support/commands.ts
  src/components/molecules/DialogWelcome/DialogWelcome.test.tsx
  src/components/molecules/DialogWelcome/DialogWelcome.test.tsx.snap
  src/components/molecules/DialogWelcome/DialogWelcome.tsx
  src/components/organisms/DialogBackup/DialogBackup.tsx
  src/components/organisms/DialogConfirmBackup/DialogConfirmBackup.tsx
Labels: 🧪 tests

#227 fix: header mobile
  src/components/molecules/Header/Header.test.tsx
  src/components/molecules/Header/Header.test.tsx.snap
  src/components/molecules/Header/Header.tsx
Labels: 🐞 bug

#206 feat: create missing nexus endpoints
  src/core/services/nexus/bootstrap/bootstrap.api.test.ts
  src/core/services/nexus/bootstrap/bootstrap.api.ts
  src/core/services/nexus/bootstrap/bootstrap.endpoints.ts
  src/core/services/nexus/bootstrap/bootstrap.test.ts
  src/core/services/nexus/bootstrap/bootstrap.ts
  src/core/services/nexus/bootstrap/index.ts
  src/core/services/nexus/file/file.api.test.ts
  src/core/services/nexus/file/file.api.ts
  src/core/services/nexus/file/file.type.ts
  src/core/services/nexus/file/index.ts
  src/core/services/nexus/index.ts
  src/core/services/nexus/nexus.types.ts
  src/core/services/nexus/nexus.utils.ts
  src/core/services/nexus/post/index.ts
  src/core/services/nexus/post/post.api.test.ts
  src/core/services/nexus/post/post.api.ts
  src/core/services/nexus/post/post.types.ts
  src/core/services/nexus/search/index.ts
  src/core/services/nexus/search/search.api.test.ts
  src/core/services/nexus/search/search.api.ts
  src/core/services/nexus/search/search.types.ts
  src/core/services/nexus/stream/posts/postStream.api.test.ts
  src/core/services/nexus/stream/posts/postStream.api.ts
  src/core/services/nexus/stream/posts/postStream.types.ts
  src/core/services/nexus/stream/users/userStream.api.test.ts
  src/core/services/nexus/stream/users/userStream.api.ts
  src/core/services/nexus/stream/users/userStream.types.ts
  src/core/services/nexus/tag/index.ts
  src/core/services/nexus/tag/tag.api.test.ts
  src/core/services/nexus/tag/tag.api.ts
  src/core/services/nexus/tag/tag.types.ts
  src/core/services/nexus/user/index.ts
  src/core/services/nexus/user/user.api.test.ts
  src/core/services/nexus/user/user.api.ts
  src/core/services/nexus/user/user.types.ts
Labels: 🔮 nexus

#229 fix: double words in mnemonic
  src/components/molecules/DialogBackupPhrase/DialogBackupPhrase.test.tsx
  src/components/molecules/DialogBackupPhrase/DialogBackupPhrase.test.tsx.snap
  src/components/molecules/DialogBackupPhrase/DialogBackupPhrase.tsx
Labels: 🐞 bug

#215 feat: nested reply link
  src/components/organisms/PostReplies/PostReplies.test.tsx
  src/components/organisms/PostReplies/PostReplies.test.tsx.snap
  src/components/organisms/PostReplies/PostReplies.tsx
Labels: 📈 enhancement

#237 tests: cleanup snapshot tests and storybooks
  src/components/organisms/AlertBackup/AlertBackup.test.tsx
  src/components/organisms/AlertBackup/AlertBackup.test.tsx.snap
  src/components/organisms/BackupMethodCard/BackupMethodCard.stories.tsx
  src/components/organisms/BackupMethodCard/BackupMethodCard.test.tsx
  src/components/organisms/BackupMethodCard/BackupMethodCard.test.tsx.snap
  src/components/organisms/ContentLayout/ContentLayout.test.tsx
  src/components/organisms/DialogBackup/DialogBackup.test.tsx
  src/components/organisms/DialogBackup/DialogBackup.test.tsx.snap
  src/components/organisms/DialogBackupEncrypted/DialogBackupEncrypted.stories.tsx
  src/components/organisms/DialogRestoreEncryptedFile/DialogRestoreEncryptedFile.stories.tsx
  src/components/organisms/DialogRestoreRecoveryPhrase/DialogRestoreRecoveryPhrase.stories.tsx
  src/components/templates/Feed/Feed.stories.tsx
Labels: 🧪 tests

#233 fix: show users pubky in PostUserDetails
  src/components/organisms/PostUserDetails/PostUserDetails.tsx
Labels: 🐞 bug

#234 fix: add date-fns and use it in PostUserDetails
  package-lock.json
  package.json
  src/components/organisms/PostUserDetails/PostUserDetails.tsx
  src/libs/utils/utils.ts
Labels: 🐞 bug

#242 feat: handle 'Enter' key to submit forms to improve UX
  src/components/molecules/InputField/InputField.tsx
  src/components/molecules/TextareaField/TextareaField.test.tsx
  src/components/molecules/TextareaField/TextareaField.tsx
  src/components/molecules/WordSlot/WordSlot.tsx
  src/components/molecules/WordSlot/WordSlot.types.ts
  src/components/organisms/DialogBackupEncrypted/DialogBackupEncrypted.test.tsx
  src/components/organisms/DialogBackupEncrypted/DialogBackupEncrypted.tsx
  src/components/organisms/DialogRestoreEncryptedFile/DialogRestoreEncryptedFile.test.tsx
  src/components/organisms/DialogRestoreEncryptedFile/DialogRestoreEncryptedFile.tsx
  src/components/organisms/DialogRestoreRecoveryPhrase/DialogRestoreRecoveryPhrase.test.tsx
  src/components/organisms/DialogRestoreRecoveryPhrase/DialogRestoreRecoveryPhrase.tsx
  src/components/organisms/HomeserverCard/HomeserverCard.test.tsx
  src/components/organisms/HomeserverCard/HomeserverCard.tsx
  src/hooks/index.ts
  src/hooks/useEnterSubmit/index.ts
  src/hooks/useEnterSubmit/useEnterSubmit.test.tsx
  src/hooks/useEnterSubmit/useEnterSubmit.ts
Labels: 📈 enhancement

#250 fix: wrong header logo on mobile
  src/components/molecules/MobileHeader/MobileHeader.test.tsx
  src/components/molecules/MobileHeader/MobileHeader.test.tsx.snap
  src/components/molecules/MobileHeader/MobileHeader.tsx
Labels: 🐞 bug

#251 test: duplicate words duplicate
  src/components/molecules/DialogBackupPhrase/DialogBackupPhrase.test.tsx
Labels: 🧪 tests

#256 fix: IndexedDB retention on logout
  src/core/controllers/auth/auth.test.ts
  src/core/controllers/auth/auth.ts
  src/core/database/franky/franky.helpers.ts
Labels: ⚙️ core

#255 fix: brand colour opacity
  src/components/atoms/Button/Button.test.tsx
  src/components/atoms/Button/Button.test.tsx.snap
  src/components/atoms/Button/Button.tsx
  src/components/molecules/ActionButtons/ActionButtons.test.tsx.snap
  src/components/molecules/ActionSection/ActionSection.test.tsx.snap
  src/components/molecules/ButtonsNavigation/ButtonsNavigation.test.tsx.snap
  src/components/molecules/Toaster/Toaster.test.tsx.snap
  src/components/molecules/Toaster/Toaster.tsx
  src/components/organisms/HomeserverCard/HomeserverCard.tsx
  src/hooks/useCopyToClipboard/useCopyToClipboard.tsx
Labels: 🎨 ui

#247 fix: backup recovery phrase visibility
  src/components/molecules/DialogBackupPhrase/DialogBackupPhrase.test.tsx
  src/components/molecules/DialogBackupPhrase/DialogBackupPhrase.tsx
Labels: 🐞 bug

#257 fix: horizontal scroll on mobile on recovery file
  src/components/organisms/DialogRestoreEncryptedFile/DialogRestoreEncryptedFile.tsx
Labels: 🎨 ui
