Repository pubky/franky, pull requests merged in 2025-09, with the labels that each got.

#87 docs: update README.md - Prep to make repo public
  README.md
Labels: 📖 documentation

#164 fix: title header page
  src/components/organisms/Header/Header.test.tsx
  src/components/organisms/Header/Header.tsx
Labels: 🐞 bug

#170 feat: add Storybook with a couple of component stories
  .gitignore
  .nvmrc
  .storybook/main.ts
  .storybook/preview.ts
  .storybook/vitest.setup.ts
  eslint.config.mjs
  package-lock.json
  package.json
  postcss.config.mjs
  src/stories/Atoms/Avatar.stories.tsx
  src/stories/Atoms/Badge.stories.tsx
  src/stories/Atoms/Button.stories.tsx
  src/stories/Atoms/Card.stories.tsx
  src/stories/Atoms/Heading.stories.tsx
  src/stories/Atoms/Input.stories.tsx
  src/stories/Molecules/InputField.stories.tsx
  src/stories/Molecules/Logo.stories.tsx
  vitest.config.ts
  vitest.shims.d.ts
Labels: 🧪 tests, ⚙️ core

#168 fix: space pubky page
  src/components/molecules/ActionSection/ActionSection.tsx
  src/components/molecules/Content/Content.tsx
Labels: 🐞 bug

#181 chore: rename profile store for auth store
  src/components/molecules/SignIn/SignIn.test.tsx
  src/components/organisms/DialogRestoreEncryptedFile/DialogRestoreEncryptedFile.test.tsx
  src/components/organisms/DialogRestoreRecoveryPhrase/DialogRestoreRecoveryPhrase.test.tsx
  src/components/organisms/Header/Header.test.tsx
  src/components/organisms/Header/Header.tsx
  src/core/controllers/auth/auth.test.ts
  src/core/controllers/auth/auth.ts
  src/core/controllers/user/user.test.ts
  src/core/controllers/user/user.ts
  src/core/services/homeserver/homeserver.test.ts
  src/core/stores/auth/auth.selectors.ts
  src/core/stores/auth/auth.store.test.ts
  src/core/stores/auth/auth.store.ts
  src/core/stores/auth/auth.ts
  src/core/stores/auth/auth.types.ts
  src/core/stores/auth/index.ts
  src/core/stores/index.ts
  src/core/stores/profile/index.ts
  src/core/stores/profile/profile.actions.ts
  src/hooks/useAuthActions/useAuthActions.tsx
  src/hooks/useAuthStatus/useAuthStatus.test.tsx
  src/hooks/useAuthStatus/useAuthStatus.tsx
Labels: 🔒 authentication, 🔄 app-state

#177 fix: color text in dialogBackupEncrypted
  src/components/molecules/DialogBackupEncrypted/DialogBackupEncrypted.tsx
Labels: 🐞 bug

#150 feat: component `Toggle`
  package-lock.json
  package.json
  src/components/atoms/Avatar/Avatar.stories.tsx
  src/components/atoms/Badge/Badge.stories.tsx
  src/components/atoms/Button/Button.stories.tsx
  src/components/atoms/Card/Card.stories.tsx
  src/components/atoms/Heading/Heading.stories.tsx
  src/components/atoms/Input/Input.stories.tsx
  src/components/atoms/Toggle/Toggle.stories.tsx
  src/components/atoms/Toggle/Toggle.test.tsx
  src/components/atoms/Toggle/Toggle.tsx
  src/components/atoms/Toggle/index.ts
  src/components/atoms/index.ts
  src/components/molecules/InputField/InputField.stories.tsx
  src/components/molecules/Logo/Logo.stories.tsx
  vitest.config.ts
Labels: 🎨 ui

#146 refactor: component `Avatar`
  src/components/atoms/Avatar/Avatar.stories.tsx
  src/components/atoms/Avatar/Avatar.test.tsx
  src/components/atoms/Avatar/Avatar.test.tsx.snap
  src/components/atoms/Avatar/Avatar.tsx
  src/components/atoms/Avatar/Avatar.types.ts
  src/components/atoms/Avatar/Avatar.variants.ts
  src/components/atoms/Avatar/index.ts
Labels: 🎨 ui

#186 feat: add project documentation for Cursor AI
  .cursor/README.md
  .cursor/component-guidelines.md
  .cursor/figma-context.md
  .cursor/project-context.md
Labels: 📖 documentation, AI

#191 feat: Add storybook deploy to github pages
  .github/workflows/storybook.yml
Labels: devops

#59 feat: dialog feedback
  src/components/molecules/DialogFeedback/DialogFeedback.stories.tsx
  src/components/molecules/DialogFeedback/DialogFeedback.test.tsx
  src/components/molecules/DialogFeedback/DialogFeedback.test.tsx.snap
  src/components/molecules/DialogFeedback/DialogFeedback.tsx
  src/components/molecules/DialogFeedback/index.ts
  src/components/molecules/index.ts
Labels: 🎨 ui

#192 feat: add filters molecules/atoms
  src/components/atoms/Filter/Filter.stories.tsx
  src/components/atoms/Filter/Filter.test.tsx
  src/components/atoms/Filter/Filter.test.tsx.snap
  src/components/atoms/Filter/Filter.tsx
  src/components/atoms/Filter/index.ts
  src/components/atoms/index.ts
  src/components/molecules/ActionButtons/ActionButtons.stories.tsx
  src/components/molecules/ActionButtons/ActionButtons.test.tsx
  src/components/molecules/ActionButtons/ActionButtons.test.tsx.snap
  src/components/molecules/ButtonsNavigation/ButtonsNavigation.stories.tsx
  src/components/molecules/ButtonsNavigation/ButtonsNavigation.test.tsx
  src/components/molecules/DialogBackupPhrase/DialogBackupPhrase.test.tsx
  src/components/molecules/FilterContent/FilterContent.stories.tsx
  src/components/molecules/FilterContent/FilterContent.test.tsx
  src/components/molecules/FilterContent/FilterContent.test.tsx.snap
  src/components/molecules/FilterContent/FilterContent.tsx
  src/components/molecules/FilterContent/index.ts
  src/components/molecules/FilterLayout/FilterLayout.stories.tsx
  src/components/molecules/FilterLayout/FilterLayout.test.tsx
  src/components/molecules/FilterLayout/FilterLayout.test.tsx.snap
  src/components/molecules/FilterLayout/FilterLayout.tsx
  src/components/molecules/FilterLayout/index.ts
  src/components/molecules/FilterReach/FilterReach.stories.tsx
  src/components/molecules/FilterReach/FilterReach.test.tsx
  src/components/molecules/FilterReach/FilterReach.test.tsx.snap
  src/components/molecules/FilterReach/FilterReach.tsx
  src/components/molecules/FilterReach/index.ts
  src/components/molecules/FilterSort/FilterSort.stories.tsx
  src/components/molecules/FilterSort/FilterSort.test.tsx
  src/components/molecules/FilterSort/FilterSort.test.tsx.snap
  src/components/molecules/FilterSort/FilterSort.tsx
  src/components/molecules/FilterSort/index.ts
  src/components/molecules/PopoverInvite/PopoverInvite.stories.tsx
  src/components/molecules/PopoverInvite/PopoverInvite.test.tsx
  src/components/molecules/PopoverInvite/PopoverInvite.test.tsx.snap
  src/components/molecules/Toaster/Toaster.test.tsx
  src/components/molecules/index.ts
  src/libs/icons/icons.test.tsx
  src/libs/icons/icons.tsx
Labels: 🎨 ui

#198 fix: small ui issues
  src/components/atoms/Dialog/Dialog.test.tsx.snap
  src/components/atoms/Dialog/Dialog.tsx
  src/components/molecules/DialogBackupEncrypted/DialogBackupEncrypted.test.tsx.snap
  src/components/molecules/DialogBackupEncrypted/DialogBackupEncrypted.tsx
  src/components/molecules/DialogBackupPhrase/DialogBackupPhrase.test.tsx.snap
  src/components/molecules/DialogBackupPhrase/DialogBackupPhrase.tsx
  src/components/organisms/DialogRestoreEncryptedFile/DialogRestoreEncryptedFile.test.tsx
  src/components/organisms/DialogRestoreEncryptedFile/DialogRestoreEncryptedFile.tsx
  src/components/organisms/DialogRestoreRecoveryPhrase/DialogRestoreRecoveryPhrase.tsx
Labels: 🐞 bug
